Algoritmo "At1 (Quetão 4)" //aqui é o nome do programa
// Disciplina  :  Lógica de Programação 
// Professor   : Rafael Lima
// Aluno : Filipe Gomes Negri

Var
v1, v2, v3, v4, rest: real


Inicio
escreva("Nota do primeiro bimestre: ")
leia(v1)//add valor digitado na variavel v1
escreva("Nota do Segundo bimestre: ")
Leia(v2)
Escreva("Nota do terceiro bimestre: ")
Leia(v3)
Escreva("Nota do quarto bimestre: ")
Leia(v4)
rest <- (v1 + v2 + v3 + v4)/4
escreva("A sua média é: ",rest)
Fimalgoritmo