Algoritmo "Atv 19"
// Disciplina  :  Lógica de Programação 
// Professor   : Rafael Lima 
// Descrição   : Mostra de 1 a 100, repetindo 5 vezes
// Autor(a)    : Filipe Gomes Negri
// Data atual  : 01/12/2021
Var
a: inteiro

Inicio
para a de 1 ate 100 faca
escreval(a)
fimpara
para a de 1 ate 100 faca
escreval(a)
fimpara
para a de 1 ate 100 faca
escreval(a)
fimpara
para a de 1 ate 100 faca
escreval(a)
fimpara
para a de 1 ate 100 faca
escreval(a)
fimpara

Fimalgoritmo