Algoritmo "Atv 21"
// Disciplina  :  Lógica de Programação 
// Professor   : Rafael Lima 
// Descrição   : Se a soma for maior que 15, o programa encerra
// Autor(a)    : Filipe Gomes Negri
// Data atual  : 06/12/2021
Var
s1, s2: Inteiro


Inicio
escreva("Informe um número: ")
leia(s1)
escreva("Informe o segundo número: ")
leia(s2)
enquanto (s1 + s2 <= 15) faca
escreva("Informe um número: ")
leia(s1)
escreva("Informe o segundo número: ")
leia(s2)
fimenquanto


Fimalgoritmo