Algoritmo "Atv 26"
// Disciplina  :  Lógica de Programação 
// Professor   : Rafael Lima 
// Descrição   : Efetua a  apresentação do valor da conversão em real, do dolar
// Autor(a)    : Filipe Gomes Negri
// Data atual  : 07/12/2021
Var
valor, r, d: real


Inicio

escreva("Digite a conotação do dólar: ")
leia(r)
escreva("Digite a sua quantidade de dólar: ")
leia(d)
valor <- d * r
escreva("Você tem em R$", valor)


Fimalgoritmo