Algoritmo "Atv1 (Questão 10)"
// Disciplina  :  Lógica de Programação 
// Professor   : Rafael Lima 
// Descrição   : Mostra aproximadamente quantos dias uma pessoa viveu
// Autor(a)    : Filipe Gomes Negri
// Data atual  : 26/11/2021
Var
idade, dias:inteiro


Inicio
escreva("Informe qual a sua idade: ")
leia(idade)
dias <- idade * 365
escreva("Você já viveu aproximadamente",dias," dias")


Fimalgoritmo