Algoritmo "Atv 1 (Questão 3)"
// Disciplina  :  Lógica de Programação 
// Professor   : Rafael Lima 
// Descrição   : Trocar os valores de X e Y.
// Autor(a)    : Filipe Gomes Negri
// Data atual  : 24/11/2021
Var
x, y, t: inteiro


Inicio
escreva("Escreva o valor de X: ")
leia(x)
escreva("Escreva o valor de Y: ")
leia(y)
t <- x
x <- y
y <- t
limpatela
Escreval("A troca ficou X = ",x)
Escreva("E Y = ",y)



Fimalgoritmo