Algoritmo "Média"
// Disciplina  :  Lógica de Programação 
// Professor   : Rafael Lima 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 29/11/2021
Var
media: real


Inicio
escreva("Informe sua média: ")
leia(media)
se (media >= 7) entao
Escreva("Aprovado:", media)
fimse
se (media <= 4) entao
escreva("Reprovado:", media)
senao
escreva("Recuperação:", media)
fimse


Fimalgoritmo